export const categories = ["All projects", "Residential", "Villas & townhouses", "Commercial", "Industrial", "Hospitality", "Civil & infrastructure"] as const;
export type Project = { slug: string; title: string; location: string; year: string; category: string; image?: string; description: string; client?: string; architect?: string; engineer?: string; source: string; service: string };
export const projects: Project[] = [
  { slug:"crescent-pearl", title:"Crescent Pearl", location:"Westlands, Nairobi", year:"2025", category:"Residential", image:"crescent-pearl-b.jpeg", description:"A residential apartment development on Crescent Road in Westlands. Crescent Pearl is also home to Dunhill’s head office.", source:"2026 company profile, page 28", service:"building" },
  { slug:"national-park-villas", title:"National Park Villas", location:"Mlolongo", year:"2025", category:"Villas & townhouses", image:"national-park-villas.jpeg", description:"A villa development in Mlolongo, featured in Dunhill’s residential portfolio.", source:"2026 company profile, page 23", service:"building" },
  { slug:"nyahururu-housing", title:"Nyahururu Housing", location:"Nyahururu", year:"2026", category:"Residential", description:"An affordable housing apartment project listed in Dunhill’s 2026 company profile.", source:"2026 company profile, page 28", service:"building" },
  { slug:"doubletree-hotel-development", title:"DoubleTree hotel development", location:"Ngong Lane, Nairobi", year:"2014", category:"Hospitality", client:"Amber Properties Ltd", architect:"Studio Infinity", engineer:"Metrix Consultancy Ltd", description:"Hotel development recorded as Double Tree by Hilton in the company’s project history.", source:"2026 company profile, page 19", service:"building" },
  { slug:"kapa-godowns-soap-plant", title:"Kapa godowns & soap plant", location:"Off Mombasa Road, Nairobi", year:"2011", category:"Industrial", client:"Kapa Oil Refineries Ltd", architect:"JAP International Ltd", engineer:"Midrock Consulting Engineers", description:"Construction of new godowns and a new soap plant for Kapa Oil Refineries, recorded in Dunhill’s industrial portfolio.", source:"2026 company profile, page 19", service:"industrial" },
  { slug:"kapa-sewer-pump-house", title:"Kapa sewer line & pump house", location:"Mombasa Road, Nairobi", year:"2009", category:"Civil & infrastructure", client:"Kapa Oil Refineries Ltd", architect:"JAP International Ltd", engineer:"Midrock Consulting Engineers", description:"Construction of a sewer line and pump house for Kapa Oil Refineries, part of the company’s civil infrastructure experience.", source:"2026 company profile, page 19", service:"civil" },
  { slug:"pms-warehousing", title:"PMS warehousing", location:"Mogadishu Road, Industrial Area", year:"To be confirmed", category:"Commercial", client:"PMS Holding", description:"Warehousing development listed in the industrial and commercial section of the company profile. The supplied project record does not specify a year.", source:"2026 company profile, page 19", service:"industrial" },
  { slug:"lavington-maisonettes", title:"24 Lavington maisonettes", location:"Lavington, Nairobi", year:"1998", category:"Villas & townhouses", client:"Jambo Holdings Ltd", architect:"Planning and Designers Associates", engineer:"Steel Graphics Associates", description:"Construction of 24 maisonettes in Lavington, one of the residential developments recorded for Jambo Holdings in Dunhill’s project history.", source:"2026 company profile, page 20", service:"building" },
];
