import type { Metadata } from "next";
import { SiteHeader } from "@/components/site-header";
import { InnerFooter } from "@/components/inner-footer";
import { EnquiryForm } from "@/components/enquiry-form";
import styles from "./contact.module.css";
export const metadata:Metadata={title:"Contact | Dunhill Building Contractors",description:"Contact Dunhill’s Westlands office or tell us about your construction project, service requirements or general enquiry."};
export const dynamic="force-dynamic";
const mapUrl="https://www.google.com/maps/search/?api=1&query=Crescent+Pearl+06+The+Crescent+Westlands+Nairobi";
export default function Contact() {
  const deliveryEnabled=Boolean(process.env.ENQUIRY_WEBHOOK_URL?.startsWith("https://") && process.env.ENQUIRY_WEBHOOK_TOKEN);
  return <><a className="skip-link" href="#main">Skip to content</a><SiteHeader onContact /><main id="main">
    <section className={`wrap ${styles.hero}`}><p className="eyebrow">Contact / Let’s start a conversation</p><div className={styles.heading}><h1>Your next chapter.<br /><em>Let’s build it together.</em></h1><p>A project taking shape, a question about our services, or something else entirely. We’d like to hear from you.</p></div><div className={styles.contactStrip}><a href="tel:+254717229495"><span>CALL OUR OFFICE</span><strong>+254 717 229 495</strong><small>Alternative: +254 722 513 547</small></a><a href="mailto:info@dunhillbcon.com"><span>EMAIL DUNHILL</span><strong>info@dunhillbcon.com</strong><small>General and project enquiries ↗</small></a><a href="#office"><span>VISIT US</span><strong>Westlands, Nairobi</strong><small>Crescent Pearl, 2nd Floor ↓</small></a></div></section>
    <section className={`wrap section ${styles.enquiry}`} id="enquiry" aria-labelledby="enquiry-title"><div className={styles.formIntro}><p className="eyebrow">01 / Your enquiry</p><h2 id="enquiry-title">Tell us<br /><em>what’s on your mind.</em></h2><p>You don’t need a finished brief to start. Share what you know, and let us know how we can help.</p><div className={styles.help}><span className="eyebrow">Useful details to include</span><ul><li>What you would like to build or discuss</li><li>Where your project is located</li><li>Your preferred timeframe</li><li>The kind of support you need</li></ul></div><p className={styles.formNote}>Prefer to speak with someone?<br /><a className="text-link" href="tel:+254722513547">Call +254 722 513 547 <span aria-hidden="true">↗</span></a></p></div><EnquiryForm deliveryEnabled={deliveryEnabled} /></section>
    <section className={styles.office} id="office" aria-labelledby="office-title"><div className="wrap"><div className="section-label"><span>02 / FIND OUR OFFICE</span><span>WESTLANDS, NAIROBI</span></div><div className={styles.officeGrid}><div><h2 id="office-title">A place<br /><em>to begin.</em></h2><address>Crescent Pearl, 2nd Floor<br />06 The Crescent, Westlands<br />Nairobi, Kenya</address><p>Please contact our team before visiting to arrange a suitable time.</p><a className="button" href={mapUrl} target="_blank" rel="noopener noreferrer">Open location in Google Maps <span aria-hidden="true">↗</span></a></div><div className={styles.mapCard}><span className="eyebrow">Office location</span><h3>Crescent Pearl</h3><p>The Crescent · Westlands</p><div className={styles.locationMark} aria-hidden="true"><svg viewBox="0 0 64 80"><path d="M32 74S7 47 7 29a25 25 0 0 1 50 0c0 18-25 45-25 45Z" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="32" cy="29" r="9" fill="none" stroke="currentColor" strokeWidth="2"/></svg></div><a className="text-link" href={mapUrl} target="_blank" rel="noopener noreferrer">View map & plan your route <span aria-hidden="true">↗</span></a><p className={styles.formNote}>Opens Google Maps in a new tab. No third-party map loads until you follow the link.</p></div></div></div></section>
    <section className={`wrap ${styles.finalContact}`} id="contact"><p className="eyebrow">Good projects start with a conversation</p><h2>Let’s talk about <em>yours.</em></h2><a className="text-link" href="#enquiry">Back to the enquiry form <span aria-hidden="true">↑</span></a></section>
  </main><InnerFooter /></>;
}
