import type { Metadata } from "next";
import { SiteHeader } from "@/components/site-header";
import { InnerFooter } from "@/components/inner-footer";
import styles from "./compliance.module.css";

export const metadata: Metadata = { title: "Compliance | Dunhill Building Contractors", description: "Request Dunhill’s contractor registration, practising licences and company documentation for your project review." };
const groups = [
  { title:"NCA Building Works", description:"Building contractor documentation for project due diligence.", documents:["Building Works registration", "Building Works practising licence"] },
  { title:"NCA Road Works", description:"Road works contractor documentation for project due diligence.", documents:["Road Works registration", "Road Works practising licence"] },
  { title:"Company documentation", description:"Corporate, business and tax documentation for your review.", documents:["Certificate of incorporation", "Business permits", "Tax compliance certificate"] },
];
const request = (title:string) => `mailto:info@dunhillbcon.com?subject=${encodeURIComponent(`Current documentation request: ${title}`)}&body=${encodeURIComponent("Hello Dunhill,\n\nPlease share the current documentation for our review.\n\nOrganisation:\nProject or tender reference:\nDocuments required:\nRequired by:\n\nThank you.")}`;

export default function Compliance() {
  return <><a className="skip-link" href="#main">Skip to content</a><SiteHeader onCompliance /><main id="main">
    <section className={`wrap ${styles.hero}`} aria-labelledby="compliance-title"><p className="eyebrow">Compliance / Company credentials</p><div className={styles.heading}><h1 id="compliance-title">Clarity builds<br /><em>confidence.</em></h1><div><p>Company credentials, clearly presented. Request the documentation you need to review Dunhill for your project.</p><a className="button" href={request("Company credentials")}>Request credentials <span aria-hidden="true">↗</span></a></div></div><div className={styles.statusPanel}><div><span className={styles.statusLabel}>PUBLIC DOCUMENT LIBRARY</span><h2>Verified first.<br /><em>Published second.</em></h2></div><div><span className={styles.badge}>Awaiting verification</span><p>No certificates or licences are currently published here. Current copies, issue and expiry details, and approval for public sharing are required before documents become available to view or download.</p><a href="#register" className="text-link">See document categories <span aria-hidden="true">↓</span></a></div></div></section>
    <section className="wrap section" id="register" aria-labelledby="register-title"><div className="section-label"><span>01 / DOCUMENT REGISTER</span><span>TRANSPARENT BY DESIGN</span></div><div className={styles.intro}><h2 id="register-title">The information<br /><em>behind the assurance.</em></h2><p>The register below lists the documents you can request. “Awaiting verification” describes their publication status on this website; it is not a finding about the company’s compliance.</p></div><div className={styles.register}>{groups.map((group,i)=><section className={styles.group} key={group.title} aria-labelledby={`group-${i}`}><div className={styles.groupHeading}><span>0{i+1}</span><h3 id={`group-${i}`}>{group.title}</h3><p>{group.description}</p></div><div>{group.documents.map(title=><article className={styles.document} key={title}><div className={styles.documentHeading}><h4>{title}</h4><span className={styles.pending}>Awaiting verification</span></div><dl><div><dt>Issue date</dt><dd>Not verified</dd></div><div><dt>Expiry / validity</dt><dd>Not verified</dd></div><div><dt>Public copy</dt><dd>Not published</dd></div></dl><a className="text-link" href={request(title)}>Request document <span className="sr-only">: {title}</span><span aria-hidden="true">↗</span></a></article>)}</div></section>)}</div><p className={styles.note}>An incorporation year is not a verified certificate issue date. Dates, document identifiers and current licence categories will be shown only after the relevant records have been checked.</p></section>
    <section className={styles.publication} aria-labelledby="publication-title"><div className="wrap"><div className="section-label"><span>02 / PUBLICATION STANDARD</span><span>CURRENT. VERIFIED. APPROVED.</span></div><h2 id="publication-title">A clear standard<br /><em>for every document.</em></h2><div className={styles.steps}>{[["Check the record", "Confirm the document belongs to Dunhill and check its issue, validity and expiry information against the relevant record."],["Approve public sharing", "Review the copy for sensitive information and obtain approval for the version that can be shared publicly."],["Keep the library current", "Publish only approved, current copies. Remove or replace documents when they expire, are superseded or need further verification."]].map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className={styles.note}>This is the publication standard for this website, not a statement that verification has already been completed.</p></div></section>
    <section className={`wrap section ${styles.faq}`} aria-labelledby="questions-title"><div><p className="eyebrow">Before you request</p><h2 id="questions-title">A little<br /><em>more clarity.</em></h2></div><div><details><summary>Why are there no download buttons yet?<span aria-hidden="true">+</span></summary><p>Public copies have not yet been verified and approved. We do not display historical profile extracts as current certificates. Use the document request links to contact our team.</p></details><details><summary>Can I request documents for a tender?<span aria-hidden="true">+</span></summary><p>Yes. Include your organisation, tender or project reference, required documents and deadline so the team can respond to your requirements.</p></details><details><summary>Does “not verified” mean a document is expired?<span aria-hidden="true">+</span></summary><p>No. It means the website does not yet have checked information suitable for publication. It does not establish whether the underlying document is valid or expired.</p></details></div></section>
    <section className={`wrap ${styles.contact}`} id="contact"><p className="eyebrow">For procurement teams, consultants & project partners</p><div><h2>Need the<br /><em>supporting documents?</em></h2><a className="button" href={request("Project due diligence")}>Request a credentials pack <span aria-hidden="true">↗</span></a></div><p>Tell us which documents you need and the project they relate to. Requests open in your email app.</p></section>
  </main><InnerFooter /></>;
}
