import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Brand, SiteHeader } from "@/components/site-header";
import { navigation, navigationHref } from "@/lib/navigation";
import styles from "./services.module.css";

export const metadata: Metadata = { title: "Services | Dunhill Building Contractors", description: "Building construction, civil engineering, industrial works, refurbishment, timber joinery and structural fabrication from Dunhill, Kenya." };
const services = [
  { id: "building", title: "Building construction", intro: "Places to live. Spaces to thrive.", copy: "Construction for residential, commercial and hospitality developments, bringing together the structure, spaces and finishing details of a building.", scope: ["Apartments, maisonettes & villas", "Office blocks & commercial buildings", "Hospitality developments"], project: "Residential experience", evidence: "The company profile records multiple maisonette developments for Jambo Holdings, including projects in Lavington and Lower Kabete." },
  { id: "civil", title: "Civil engineering & road works", intro: "The infrastructure beneath everyday life.", copy: "Civil works for the infrastructure that supports buildings, sites and communities. Talk to us about the requirements and delivery scope of your scheme.", scope: ["Road works & associated infrastructure", "Drainage & sewer infrastructure", "Culverts & associated structures"], project: "Infrastructure experience", evidence: "Sewer line and pump house construction for Kapa Oil Refineries is recorded in the profile’s 2009 project history." },
  { id: "industrial", title: "Industrial construction", intro: "Built around the way business works.", copy: "Construction for storage, production and industrial operations, with civil and building expertise connected to the practical needs of each facility.", scope: ["Warehouses & godowns", "Industrial plants", "Associated civil works"], project: "Industrial experience", evidence: "The profile records new godowns and a soap plant for Kapa Oil Refineries in 2011, alongside industrial work at Athi River." },
  { id: "renovation", title: "Renovation & refurbishment", intro: "New possibilities for existing places.", copy: "Alterations and upgrades that give existing buildings a new chapter. The scope starts with understanding the property, its condition and your plans.", scope: ["Building alterations", "Refurbishment & upgrades", "Repairs to existing buildings"], project: "Discuss a comparable project", evidence: "Tell us about your building and the proposed work. We can discuss relevant experience and the information needed to define your scope." },
  { id: "joinery", title: "Timber joinery", intro: "Craft in the details you live with.", copy: "Our timber workshop supports construction and finishing with fabricated joinery elements for interiors and building openings.", scope: ["Window & door frames", "Panel doors & handrails", "Shelves & cabinets"], project: "Workshop capability", evidence: "These joinery capabilities are listed in the company profile. Ask our team for relevant examples and project-specific requirements." },
  { id: "fabrication", title: "Metal & structural fabrication", intro: "Precision, from frame to finish.", copy: "Metal workshop capabilities support building components and structural steelwork, connecting specialist fabrication with construction needs.", scope: ["Metal windows, doors & grills", "Gratings & frames", "Structural steelwork"], project: "Workshop capability", evidence: "The profile lists a fully equipped metal workshop for these fabrication services. Contact us for examples relevant to your project." },
];
const enquiry = (service: string) => `mailto:info@dunhillbcon.com?subject=${encodeURIComponent(`${service} enquiry`)}`;

export default function Services() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a><SiteHeader onServices />
    <main id="main">
      <section className={`wrap ${styles.hero}`} aria-labelledby="services-title">
        <p className="eyebrow">Our services / Connected expertise</p>
        <div className={styles.heading}><h1 id="services-title">From the ground up.<br /><em>To the finest detail.</em></h1><div><p>Construction, engineering and specialist workshops. Expertise for the whole project, with care for every part.</p><a className="button" href="#service-directory">Find your service <span aria-hidden="true">↓</span></a></div></div>
        <div className={styles.cover}><Image src="/images/profile/industrial-01.jpeg" alt="Steel erection and lifting equipment on a Dunhill construction site" fill preload sizes="(max-width: 800px) 100vw, 90vw" /><div><span>ON SITE. IN THE WORKSHOP.</span><strong>Expertise that<br />works together.</strong></div><span className={styles.coverLabel}>BUILDING · ENGINEERING · FABRICATION</span></div>
        <nav className={styles.directory} id="service-directory" aria-label="Explore services">{services.map((service, i) => <a key={service.id} href={`#${service.id}`}><span>0{i+1}</span><strong>{service.title}</strong><span aria-hidden="true">↗</span></a>)}</nav>
      </section>
      <section className="wrap section" aria-labelledby="expertise-title"><div className="section-label"><span>01 / WHAT WE DO</span><span>SIX CONNECTED SERVICES</span></div><h2 id="expertise-title">The right expertise.<br /><em>For what comes next.</em></h2><div className={styles.services}>{services.map((service, i) => <article id={service.id} key={service.id} className={styles.service}><div className={styles.serviceTitle}><span className="eyebrow">SERVICE / 0{i+1}</span><h3>{service.title}</h3><p>{service.intro}</p></div><div className={styles.serviceBody}><p>{service.copy}</p><ul>{service.scope.map(item => <li key={item}>{item}</li>)}</ul><a className="text-link" href={enquiry(service.title)}>Discuss {service.id === "civil" ? "civil works" : service.title.toLowerCase()} <span aria-hidden="true">↗</span></a></div><aside className={styles.evidence}><span className="eyebrow">{service.project}</span><p>{service.evidence}</p>{i < 3 ? <Link href="/projects">Explore selected work <span aria-hidden="true">↗</span></Link> : <a href={enquiry(`${service.title} examples`)}>Request relevant examples <span aria-hidden="true">↗</span></a>}</aside></article>)}</div></section>
      <section className={styles.resources} aria-labelledby="resources-title"><div className="wrap"><div className="section-label"><span>02 / BEHIND THE DELIVERY</span><span>PEOPLE, PLANT & WORKSHOPS</span></div><div className={styles.resourceHeading}><h2 id="resources-title">More than a service.<br /><em>The resources behind it.</em></h2><p>Our construction expertise is supported by plant, specialist workshops and a team spanning engineering, operations, finance and on-site trades.</p></div><div className={styles.resourceGrid}>{[["01", "Plant & machinery", "Equipment listed in the profile includes excavators, loaders, rollers, concrete mixers and lifting equipment."], ["02", "Specialist workshops", "Timber joinery and metal fabrication facilities support the building process through to finishing."], ["03", "People & coordination", "Leadership and technical roles connect project engineering, quantity surveying, workshop management and site supervision."]].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className={styles.resourceLinks}><Link className="text-link" href="/plant-workshops">Explore plant & workshops <span aria-hidden="true">↗</span></Link><Link className="text-link" href="/about">Meet Dunhill <span aria-hidden="true">↗</span></Link></div><p className={styles.note}>Resources and availability are agreed against the scope and programme of each project.</p></div></section>
      <section className={`wrap ${styles.contact}`} id="contact"><p className="eyebrow">Let’s talk about your requirements</p><div><h2>Your plans.<br /><em>Our next conversation.</em></h2><div><p>Share your location, the work you have in mind and any drawings or project requirements you already have.</p><a className="button" href={enquiry("New project")}>Start a project <span aria-hidden="true">↗</span></a></div></div></section>
    </main>
    <footer className="footer"><div className="wrap footer-main"><div><Link href="/" aria-label="Dunhill home"><Brand /></Link><p>Building excellence.<br />Creating landmarks.</p></div><nav aria-label="Footer navigation">{navigation.map(([label,id])=><Link key={id} href={navigationHref(id,true)}>{label}</Link>)}<Link href="/contact">Contact</Link></nav><address><span className="eyebrow">Find us</span>Crescent Pearl, 2nd Floor<br />06 The Crescent, Westlands<br />Nairobi, Kenya</address></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Dunhill Building Contractors Ltd</span><a href="#main">Back to top ↑</a></div></footer>
  </>;
}
