import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { InnerFooter } from "@/components/inner-footer";
import styles from "./plant.module.css";

export const metadata: Metadata = { title: "Plant & Workshops | Dunhill Building Contractors", description: "Explore Dunhill’s construction equipment, transport, site resources, timber joinery and metal fabrication workshops." };
const equipment = [
  ["Earthmoving equipment", "Preparing the ground.", "Excavators, wheel loaders and earthmoving machinery.", "Supports excavation, material handling and preparation of construction areas."],
  ["Transport vehicles", "Keeping the site connected.", "Lorries, tippers, Mitsubishi Canter trucks and pickup vehicles.", "Supports movement of materials, equipment and site personnel between locations."],
  ["Concrete equipment", "From mixing to placement.", "Concrete mixers, vibrators, pokers and dumpers.", "Supports concrete preparation, movement and consolidation during construction."],
  ["Compaction machinery", "A firm foundation for the work.", "Rollers and compactor plates.", "Supports compaction of suitable fill and prepared surfaces for civil and building works."],
  ["Lifting equipment", "Supporting work at height.", "Hoists and cranes listed in the company’s equipment inventory.", "Supports lifting and positioning of construction materials, with arrangements defined for each project."],
  ["Power & supporting resources", "The essentials behind progress.", "Generators, water pumps, formwork equipment, steel plates and steel jacks.", "Supports site power, water handling, temporary works and the practical needs of construction."],
];
export default function PlantWorkshops() {
  return <><a className="skip-link" href="#main">Skip to content</a><SiteHeader onPlant /><main id="main">
    <section className={`wrap ${styles.hero}`} aria-labelledby="plant-title"><p className="eyebrow">Plant & workshops / Behind the build</p><div className={styles.heading}><h1 id="plant-title">The resources.<br /><em>The readiness.</em></h1><div><p>From earthmoving to the finishing details, our plant and workshops support the people delivering the work.</p><a className="text-link" href="#equipment">Explore our resources <span aria-hidden="true">↓</span></a></div></div><figure className={styles.cover}><Image unoptimized src="/images/profile/industrial-03.jpeg" alt="A loader and roller beside a steel-framed building under construction" fill preload sizes="90vw" /><figcaption><span>ON SITE / FROM THE COMPANY PROFILE</span><strong>Capability you can see.</strong></figcaption></figure><nav className={styles.jump} aria-label="Explore plant and workshops"><a href="#equipment"><span>01</span>Plant & equipment <span aria-hidden="true">↗</span></a><a href="#workshops"><span>02</span>Our workshops <span aria-hidden="true">↗</span></a><a href="#delivery"><span>03</span>Supporting delivery <span aria-hidden="true">↗</span></a></nav></section>
    <section className="wrap section" id="equipment" aria-labelledby="equipment-title"><div className="section-label"><span>01 / PLANT & EQUIPMENT</span><span>RESOURCES FOR THE WORK AHEAD</span></div><div className={styles.intro}><h2 id="equipment-title">Equipped for<br /><em>the task at hand.</em></h2><p>A range of equipment supports site preparation, construction and finishing. The selection below reflects the company profile; deployment is agreed against each project’s scope and programme.</p></div><div className={styles.inventory}>{equipment.map(([title,tagline,items,benefit],i)=><article key={title}><span className={styles.number}>0{i+1}</span><h3>{title}</h3><p className={styles.tagline}>{tagline}</p><p>{items}</p><details><summary>How it supports delivery <span aria-hidden="true">+</span></summary><p>{benefit}</p></details></article>)}</div><p className={styles.note}>Equipment types are drawn from the 2026 company profile. Current quantities, specifications and availability should be confirmed with our team.</p></section>
    <section className={styles.workshops} id="workshops" aria-labelledby="workshop-title"><div className="wrap"><div className="section-label"><span>02 / SPECIALIST WORKSHOPS</span><span>CRAFT & CONSTRUCTION, CONNECTED</span></div><div className={styles.intro}><h2 id="workshop-title">Made with care.<br /><em>Built into the detail.</em></h2><p>Our timber joinery and metal fabrication workshops extend our capabilities beyond the site, supporting building components and finishing work.</p></div><div className={styles.workshopGrid}><article><span className="eyebrow">Workshop / 01</span><h3>Timber joinery</h3><p>Joinery for building openings, interiors and finishing details, produced through the timber workshop described in our company profile.</p><ul><li>Window and door frames</li><li>Panel doors and handrails</li><li>Shelves and cabinets</li></ul><Link className="text-link" href="/services#joinery">Explore timber joinery <span aria-hidden="true">↗</span></Link></article><article><span className="eyebrow">Workshop / 02</span><h3>Metal fabrication</h3><p>Metal components and structural steelwork that connect specialist fabrication with the needs of building construction.</p><ul><li>Metal windows, grills and doors</li><li>Gratings and frames</li><li>Structural steelwork</li></ul><Link className="text-link" href="/services#fabrication">Explore metal fabrication <span aria-hidden="true">↗</span></Link></article></div><div className={styles.photoNotice}><span>WORKSHOP PHOTOGRAPHY</span><p>Approved photographs of the timber and metal workshops will be added here. The photographs elsewhere on this page show construction sites, not workshop interiors.</p></div></div></section>
    <section className="wrap section" aria-labelledby="site-title"><div className="section-label"><span>03 / RESOURCES IN CONTEXT</span><span>FROM THE COMPANY PROFILE</span></div><h2 id="site-title">Where capability<br /><em>meets the work.</em></h2><div className={styles.gallery}><figure><div><Image unoptimized src="/images/profile/industrial-01.jpeg" alt="Lifting equipment alongside steel columns during construction" fill sizes="(max-width: 800px) 90vw, 55vw" /></div><figcaption><span>01 / ON-SITE LIFTING</span><p>Lifting equipment supporting steel erection.</p></figcaption></figure><figure><div><Image unoptimized src="/images/profile/industrial-04.jpeg" alt="Concrete floor within a steel-framed building under construction" fill sizes="(max-width: 800px) 90vw, 35vw" /></div><figcaption><span>02 / BUILDING WORKS</span><p>Concrete flooring within a structural steel frame.</p></figcaption></figure></div></section>
    <section className={`wrap ${styles.delivery}`} id="delivery" aria-labelledby="delivery-title"><div className="section-label"><span>04 / SUPPORTING PROJECT DELIVERY</span><span>CONNECTED RESOURCES</span></div><div className={styles.intro}><h2 id="delivery-title">The right resources.<br /><em>A coordinated approach.</em></h2><p>Plant and workshops are part of a wider delivery team. Their value comes from matching the equipment, fabrication requirements and site activities to the work being undertaken.</p></div><ol className={styles.steps}>{[["Understand the requirements", "Identify the work, site conditions, access and programme that inform resource needs."],["Coordinate the resources", "Bring equipment needs and workshop requirements into the project’s delivery planning."],["Connect workshop and site", "Coordinate fabricated components with site activities and the agreed construction sequence."]].map(([title,copy],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol><Link className="text-link" href="/projects">See our project experience <span aria-hidden="true">↗</span></Link></section>
    <section className={`wrap ${styles.contact}`} id="contact"><p className="eyebrow">Let’s discuss the practical details</p><div><h2>What does your<br /><em>project need?</em></h2><a className="button" href="mailto:info@dunhillbcon.com?subject=Plant%20and%20workshop%20project%20enquiry">Discuss your requirements <span aria-hidden="true">↗</span></a></div><p>Share your scope, location and programme so our team can discuss relevant resources and availability.</p></section>
  </main><InnerFooter /></>;
}
